config/routes.rb
Rails.application.routes.draw do

  
  get 'doortags/related'
  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'
get "sessions/new"
get "sessions/create"
get "sessions/destroy"
post "sessions/create"
  get 'sessions/login_attempt'
  post 'sessions/login_attempt'
  
get 'users/edit'
  get 'switpost/new'
  post 'switpost/new'
  get 'post/index'
  get 'sessions/new'
  get 'welcome/index'

  get 'users/index'
  get 'users/new'
  root to: 'users#new'

resources :user_sessions
resources :users
resources :post

resources :articles do
  resources :comments, :users, :sweets, :sours, :doortags
end


get '/door_tag' => 'doortags#related'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	 has_many :comments, dependent: :destroy
	 has_many :sweets
	 has_many :sours
	 
	 validates :title, presence: true,
                    length: { minimum: 5 }


     #acts_as_likeable
     #acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/doortag.rb
class Doortag < ActiveRecord::Base
end

app/models/sour.rb
class Sour < ActiveRecord::Base
	
    belongs_to :article
end

app/models/sweet.rb
class Sweet < ActiveRecord::Base
	
    belongs_to :article
end

app/models/swit_talks.rb
class SwitTalks < ActiveRecord::Base
end

app/models/switter.rb
class Switter < ActiveRecord::Base
end

app/models/switterapp.rb
class Switterapp < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
 
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create
 
 has_many :articles
 

protected
  
  def password_required?
    logger.warn('checking if the password is required: '+ updating_password)
    if updating_password.to_i > 0
      true
    else
      false
    end
  end
end

app/models/welcom.rb
class Welcom < ActiveRecord::Base
end

app/controllers/doortags_controller.rb
class DoortagsController < ApplicationController
  before_action :set_doortag, only: [:show, :edit, :update, :destroy]

  # GET /doortags
  # GET /doortags.json
  def index
    @doortags = Doortag.all
  end

  # GET /doortags/1
  # GET /doortags/1.json
  def show
  end

  # GET /doortags/new
  def new
    @doortag = Doortag.new
  end

  # GET /doortags/1/edit
  def edit
  end

  # POST /doortags
  # POST /doortags.json
  def create
    @doortag = Doortag.new(doortag_params)

    respond_to do |format|
      if @doortag.save
        format.html { redirect_to @doortag, notice: 'Doortag was successfully created.' }
        format.json { render :show, status: :created, location: @doortag }
      else
        format.html { render :new }
        format.json { render json: @doortag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doortags/1
  # PATCH/PUT /doortags/1.json
  def update
    respond_to do |format|
      if @doortag.update(doortag_params)
        format.html { redirect_to @doortag, notice: 'Doortag was successfully updated.' }
        format.json { render :show, status: :ok, location: @doortag }
      else
        format.html { render :edit }
        format.json { render json: @doortag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doortags/1
  # DELETE /doortags/1.json
  def destroy
    @doortag.destroy
    respond_to do |format|
      format.html { redirect_to doortags_url }
      format.json { head :no_content }
    end
  end

  def related
    @tag=params[:tag]
    @articles= Article.all
    @doortags= Doortag.where(tag: @tag)

    render 'doortags/related'
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doortag
      @doortag = Doortag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doortag_params
      params.require(:doortag).permit(:article_id, :tag)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/doortags_helper.rb
module DoortagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sour_helper.rb
module SourHelper
end

app/helpers/sours_helper.rb
module SoursHelper
end

app/helpers/sweet_helper.rb
module SweetHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcoms_helper.rb
module WelcomsHelper
end

app/views/doortags/_related.html.erb
<div id="body">
<br/><br/><br/><br/><br/><p>hello</p>
<% @doortags.each do |doortag| %>

<%= doortag.tag %>
<%= @articles.where(id: doortag.article_id).first.text %>
<%= doortag.article_id %>
<%end%>

</div>

app/views/doortags/edit.html.haml
%h1 Editing doortag

= render 'form'

= link_to 'Show', @doortag
\|
= link_to 'Back', doortags_path

app/views/doortags/index.html.haml
%h1 Listing doortags

%table
  %tr
    %th Article
    %th Tag
    %th
    %th
    %th

  - @doortags.each do |doortag|
    %tr
      %td= doortag.article_id
      %td= doortag.tag
      %td= link_to 'Show', doortag
      %td= link_to 'Edit', edit_doortag_path(doortag)
      %td= link_to 'Destroy', doortag, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Doortag', new_doortag_path

app/views/doortags/new.html.haml
%h1 New doortag

= render 'form'

= link_to 'Back', doortags_path

app/views/doortags/related.html.erb
<div id="body1">
<br/><br/><br/><br/><br/>
<div id="fonts">
	<%= image_tag("posts.jpg", :alt => "rss feed") %>
</div>

<div id="doortags">

<% @doortags.each do |doortag| %>
<div id="articles">
<div id="thumb"><%= image_tag("download.jpeg", :alt => "rss feed") %></div>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<strong><%= @articles.where(id: doortag.article_id).first.title %></strong>
<div id="commented"><br/>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp&nbsp&nbspPosted <%= time_ago_in_words(@articles.where(id: doortag.article_id).first.created_at) %> ago</div>
<p>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp&nbsp&nbsp<%= @articles.where(id: doortag.article_id).first.text %>

</p>
<hr>

<%end%>
</div>
</div>

app/views/doortags/show.html.haml
%p#notice= notice

%p
  %b Article:
  = @doortag.article_id
%p
  %b Tag:
  = @doortag.tag

= link_to 'Edit', edit_doortag_path(@doortag)
\|
= link_to 'Back', doortags_path