config/routes.rb
Rails.application.routes.draw do

  
  get 'doortags/related'
  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'
get "sessions/new"
get "sessions/create"
get "sessions/destroy"
post "sessions/create"
  get 'sessions/login_attempt'
  post 'sessions/login_attempt'
  
get 'users/edit'
  get 'switpost/new'
  post 'switpost/new'
  get 'post/index'
  get 'sessions/new'
  get 'welcome/index'

  get 'users/index'
  get 'users/new'
  root to: 'users#new'

resources :user_sessions
resources :users
resources :post

resources :articles do
  resources :comments, :users, :sweets, :sours, :doortags
end


get '/door_tag' => 'doortags#related'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	 has_many :comments, dependent: :destroy
	 has_many :sweets
	 has_many :sours
	 
	 validates :title, presence: true,
                    length: { minimum: 5 }


     #acts_as_likeable
     #acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/doortag.rb
class Doortag < ActiveRecord::Base
end

app/models/sour.rb
class Sour < ActiveRecord::Base
	
    belongs_to :article
end

app/models/sweet.rb
class Sweet < ActiveRecord::Base
	
    belongs_to :article
end

app/models/swit_talks.rb
class SwitTalks < ActiveRecord::Base
end

app/models/switter.rb
class Switter < ActiveRecord::Base
end

app/models/switterapp.rb
class Switterapp < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
 
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create
 
 has_many :articles
 

protected
  
  def password_required?
    logger.warn('checking if the password is required: '+ updating_password)
    if updating_password.to_i > 0
      true
    else
      false
    end
  end
end

app/models/welcom.rb
class Welcom < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 
def new
	@article = Article.new
	end

def show

  @article = Article.find(params[:id])
  
end
def edit
	@article = Article.find(params[:id])
end
def index
  @article = Article.new
  @articles = Article.all.order('created_at desc')
end
def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end
def create
  @article = Article.new(article_params)
 
  if @article.save
    @tags = @article.text.scan(/\{[^}]*\}/)
    @tags.each do |doortag|
        
        doortag=doortag.gsub(/\{/,"")
        doortag=doortag.gsub(/\}/,"")
        @doortag = Doortag.create(article_id: @article.id, tag: doortag)
        @doortag.save
 end
 
    redirect_to articles_path

  else
    render 'new'
  end
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to articles_path
  else
    render 'edit'
  end
end
private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/doortags_helper.rb
module DoortagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sour_helper.rb
module SourHelper
end

app/helpers/sours_helper.rb
module SoursHelper
end

app/helpers/sweet_helper.rb
module SweetHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcoms_helper.rb
module WelcomsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div id="article">
     <div class="small-12 columns">
  <p>
    <%= f.hidden_field :title, :value => current_user.username %>
  </p>
 
    <div id="create_swit">
    Create a Swit
  </div>
      <p>
    <%= f.text_area :text , :id => "txt", :maxlength => 140 %>
 Characters remaining: <span id="count"> 140</span>
  </p>

  
 <div class=""><%= f.submit "Submit", :class => 'button tiny push-7' %> </div>
    
</div>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div id="body">
<br/>

<%= render 'form' %>


<div id="swits">

<% for article in @articles %>
 <div id="articles">
<div id="thumb"><%= image_tag("download.jpeg", :alt => "rss feed") %></div>
<br/>
<% text = article.text %>
<% article.text.scan(/{(.*?)}/) do |f| %>

              <% text = text.gsub('{' + f[0] + '}', "<a data-method=\"get\" href=\"\/door_tag\?tag=" + f[0] + "\">\{" + f[0] + "\}</a>").html_safe  %>


<% end %>



<strong>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp&nbsp&nbsp<%= article.title %></strong>
  <div id="commented"><br/>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp&nbsp&nbsp&nbspPosted <%= time_ago_in_words(article.created_at) %> ago</div>
  <br/>
  <p>&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<%= text %></p>
  
  <p>
<% @sweet= Sweet.new%>
<%= form_for([article, @sweet], :html => {:class => 'sweet_form'}) do |f| %>
  <% if @sweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>
      <ul>
      <% @sweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <input id="sweet_article_id" name="sweet[article_id]" type="hidden" value="<%= @article.id%>" />
 &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<input name="commit" type="submit" class= "button tiny" value="Sweet" />
<% end %>
</p>

<div id="sour">
<% @sour= Sour.new%>

<%= form_for([article, @sour], :html => {:class => 'sour_form'}) do |f| %>
  <% if @sour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sour.errors.count, "error") %> prohibited this sour from being saved:</h2>

      <ul>
      <% @sour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sour_article_id" name="sour[article_id]" type="hidden" value="<%= @article.id%>" />
  &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<input name="commit" type="submit" class= "button tiny" value="Sour" />
<% end %>

</div>
<div id="sweetour">
&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<%= link_to pluralize(article.sweets.count.to_s, "sweet")%> &nbsp |  &nbsp    

<%= link_to pluralize(article.sours.count.to_s, "sour")%> &nbsp  | &nbsp 

<%= link_to 'Delete', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</p>

<hr>
</div>
<div id="commentsSection">


<%=render :partial => article.comments %>
<br/>
 <%= form_for([article, article.comments.build],  :remote => true )   do |f| %>
  <%= f.hidden_field :commenter, :value => current_user.username %>
  <div id="commentbox">
    
    <%= f.text_area :body , placeholder: "Enter comment", :class => "small-9 columns"%>
  </div>
  <p>
    <%= f.submit :Comment, :class => "button tiny" %>
  </p>
<% end %>                   


<br/>
</div>
<% end %>

</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render 'form' %>
<p>
  <strong>Author:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

 <strong>Posted <%= time_ago_in_words(@article.created_at) %> ago by <%= @article.title %></strong>

<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>